pipeline:
  test:
    image: node:latest
    commands:
      - npm install
      - npm run lint
  build:
    image: node:latest
    secrets: [ GH_TOKEN ]
    environment:
      - GH_TOKEN=${GH_TOKEN}
    commands:
      - npm install
      - npm run build
      - ./deploy
    when:
      branch: master
