pipeline:
  test:
    image: node:latest
    commands:
      - npm install
      - npm run lint
    when:
      branch:
        exclude: gh-pages

  build:
    image: node:latest
    secrets: [ GH_TOKEN ]
    environment:
      - GH_TOKEN=${GH_TOKEN}
    commands:
      - npm install
      - npm run build
      - ./deploy
    when:
      event: [push, tag, deployment]
      branch: master
