pipeline:
  test:
    image: node:latest
    commands:
      - npm install
      - npm run lint
    when:
      branch:
        exclude: gh-pages

  build:
    image: node:latest
    secrets: [ GH_TOKEN, SSH_KEY, SSH_PUB ]
    environment:
      - GH_TOKEN=${GH_TOKEN}
      - SSH_KEY=${SSH_KEY}
      - SSH_PUB=${SSH_PUB}
    commands:
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_dsa && echo "$SSH_PUB" > /root/.ssh/id_dsa.pub
      - chmod -R 0600 /root/.ssh/id_rsa && chmod -R 0755 /root/.ssh/id_rsa.pub
      - npm install
      - npm run build
      - ./deploy
    when:
      event: [push, tag, deployment]
      branch: master
