#!/usr/bin/sh
git fetch && git merge master
git branch -D gh-pages 2>/dev/null || true
git branch -D draft 2>/dev/null || true
git checkout -b draft
git add -f dist
git commit -am "Deploy on gh-pages"
git subtree split --prefix dist -b gh-pages
git push --force gh-pages:gh-pages > /dev/null 2>&1
