#!/usr/bin/env bash
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
git config user.name "Ukulele"
git config user.email "ukulele@hackyourfuture.net"
git fetch && git merge master
git branch -D gh-pages 2>/dev/null || true
git branch -D draft 2>/dev/null || true
git checkout -b draft
git add -f dist
git commit -am "Deploy on gh-pages"
git subtree split --prefix dist -b gh-pages
git push --force git@github.com:HackYourFuture/Iraq.git gh-pages:gh-pages
