#!/usr/bin/env node
const gh = require('gh-pages')

gh.publish('dist', {
  branch: 'gh-pages',
  repo: 'git@github.com:HackYourFuture/Iraq.git',
  user: {
    name: 'ideabile-ci',
    email: 'drone@ideabile.com'
  }
}, (err) => {
   console.log(err);
});
